apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-page
  labels:
    app: green-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green-page
  template:
    metadata:
      labels:
        app: green-page
    spec:
      containers:
        - name: green-page
          image: pedrofuques/green-page:5725
          ports:
            - containerPort: 80
