apiVersion: v1
kind: Service
metadata:
  name: green-page-service
spec:
  type: LoadBalancer # Change to NodePort if using Minikube
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: green-page
